// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoraCricketHub.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MoraCricketHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260416093513_AutoEventsAndPartnershipTracking")]
    partial class AutoEventsAndPartnershipTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.BowlingMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("Delivery1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Delivery2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Delivery3Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<string>("MilestoneType")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Delivery1Id");

                    b.HasIndex("Delivery2Id");

                    b.HasIndex("Delivery3Id");

                    b.HasIndex("InningsId");

                    b.HasIndex("MilestoneType");

                    b.HasIndex("PlayerId");

                    b.ToTable("BowlingMilestones");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Delivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallNumber")
                        .HasColumnType("integer");

                    b.Property<string>("BowlingSide")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliverySequence")
                        .HasColumnType("integer");

                    b.Property<string>("DirectionZone")
                        .HasColumnType("text");

                    b.Property<string>("DismissedBatterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("DismissedMoraBatterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DismissedOppBatterId")
                        .HasColumnType("uuid");

                    b.Property<int>("ExtrasRuns")
                        .HasColumnType("integer");

                    b.Property<string>("ExtrasType")
                        .HasColumnType("text");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsMidOverBowlerChange")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWicket")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MoraBatterId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoraBowlerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoraFielderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OppBatterId")
                        .HasColumnType("uuid");

                    b.Property<string>("OppBatterName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OppBatterStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid?>("OppBowlerId")
                        .HasColumnType("uuid");

                    b.Property<string>("OppBowlerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OppBowlerStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("OppFielderName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OverNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RunsOffBat")
                        .HasColumnType("integer");

                    b.Property<string>("ShotType")
                        .HasColumnType("text");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WicketType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DismissedMoraBatterId");

                    b.HasIndex("DismissedOppBatterId");

                    b.HasIndex("InningsId");

                    b.HasIndex("IsWicket");

                    b.HasIndex("MoraBatterId");

                    b.HasIndex("MoraBowlerId");

                    b.HasIndex("MoraFielderId");

                    b.HasIndex("OppBatterId");

                    b.HasIndex("OppBatterStyle");

                    b.HasIndex("OppBowlerId");

                    b.HasIndex("OppBowlerStyle");

                    b.HasIndex("InningsId", "OverNumber", "DeliverySequence")
                        .IsUnique();

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.FallOfWicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DismissedMoraPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DismissedOppPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DismissedPlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OverAtFall")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("ScoreAtFall")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WicketNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DismissedMoraPlayerId");

                    b.HasIndex("DismissedOppPlayerId");

                    b.HasIndex("InningsId");

                    b.HasIndex("InningsId", "WicketNumber")
                        .IsUnique();

                    b.ToTable("FallOfWickets");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Innings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BattingTeam")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CommentaryCoverage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EndedAtOver")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("ExtrasByes")
                        .HasColumnType("integer");

                    b.Property<int>("ExtrasLegByes")
                        .HasColumnType("integer");

                    b.Property<int>("ExtrasNoBalls")
                        .HasColumnType("integer");

                    b.Property<int>("ExtrasPenalty")
                        .HasColumnType("integer");

                    b.Property<int>("ExtrasWides")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDeliveryData")
                        .HasColumnType("boolean");

                    b.Property<int>("InningsNumber")
                        .HasColumnType("integer");

                    b.Property<string>("InningsType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("MaxOvers")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MoraWickeeperId")
                        .HasColumnType("uuid");

                    b.Property<int>("ScheduledOvers")
                        .HasColumnType("integer");

                    b.Property<int?>("Target")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalOversFaced")
                        .HasColumnType("decimal(4,1)");

                    b.Property<int>("TotalRuns")
                        .HasColumnType("integer");

                    b.Property<int>("TotalWickets")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattingTeam");

                    b.HasIndex("HasDeliveryData");

                    b.HasIndex("MatchId");

                    b.HasIndex("MoraWickeeperId");

                    b.ToTable("Innings");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.InningsEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("AtOver")
                        .HasColumnType("decimal(4,1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RevisedOvers")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamScoreAtEvent")
                        .HasColumnType("integer");

                    b.Property<int?>("TeamWicketsAtEvent")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventType");

                    b.HasIndex("InningsId");

                    b.HasIndex("PlayerId");

                    b.ToTable("InningsEvents");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BallColour")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("BallType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DlsApplied")
                        .HasColumnType("boolean");

                    b.Property<int?>("DlsTarget")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date");

                    b.Property<bool?>("MoraBattingFirst")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MoraCaptainId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoraWickeeperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("OpponentCaptainName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlayerOfMatchMoraId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerOfMatchName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PlayerOfMatchTeam")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("ResultMargin")
                        .HasColumnType("integer");

                    b.Property<string>("ResultMarginType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ResultType")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int?>("RevisedOvers")
                        .HasColumnType("integer");

                    b.Property<string>("RoundLabel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RoundType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ScheduledOvers")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("SurfaceType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("TossDecision")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<bool>("TossHeld")
                        .HasColumnType("boolean");

                    b.Property<string>("TossWinner")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("VenueId")
                        .HasColumnType("uuid");

                    b.Property<string>("VenueType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("MatchDate");

                    b.HasIndex("MoraBattingFirst");

                    b.HasIndex("MoraCaptainId");

                    b.HasIndex("MoraWickeeperId");

                    b.HasIndex("OpponentId");

                    b.HasIndex("PlayerOfMatchMoraId");

                    b.HasIndex("ResultType");

                    b.HasIndex("Status");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VenueId");

                    b.HasIndex("VenueType");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MatchOpponentSquad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("BattingOrder")
                        .HasColumnType("integer");

                    b.Property<string>("BattingStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("BowlingStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OpponentPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("OpponentPlayerId");

                    b.ToTable("MatchOpponentSquads");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MatchSquad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPlayingXi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique();

                    b.ToTable("MatchSquads");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBattingOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("InningsId", "PlayerId")
                        .IsUnique();

                    b.HasIndex("InningsId", "Position")
                        .IsUnique();

                    b.ToTable("MoraBattingOrders");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBattingPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsFaced")
                        .HasColumnType("integer");

                    b.Property<int>("BattingPosition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissalType")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid?>("DismissedByOppBowlerId")
                        .HasColumnType("uuid");

                    b.Property<string>("DismissedByOppBowlerName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DismissedByOppBowlerStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid?>("FieldedByMoraPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("FieldedByOppName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Fours")
                        .HasColumnType("integer");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDuck")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFifty")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHundred")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNotOut")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThirty")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinutesBatted")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Sixes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DismissedByOppBowlerId");

                    b.HasIndex("DismissedByOppBowlerStyle");

                    b.HasIndex("FieldedByMoraPlayerId");

                    b.HasIndex("InningsId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MoraBattingPerformances");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBowlingPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsFiveWicketHaul")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFourWicketHaul")
                        .HasColumnType("boolean");

                    b.Property<int>("Maidens")
                        .HasColumnType("integer");

                    b.Property<int>("NoBalls")
                        .HasColumnType("integer");

                    b.Property<decimal>("OversBowled")
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunsConceded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wickets")
                        .HasColumnType("integer");

                    b.Property<int>("Wides")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InningsId");

                    b.HasIndex("IsFiveWicketHaul");

                    b.HasIndex("PlayerId");

                    b.ToTable("MoraBowlingPerformances");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraFieldingPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Catches")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DroppedCatches")
                        .HasColumnType("integer");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("RunOuts")
                        .HasColumnType("integer");

                    b.Property<int>("Stumpings")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("InningsId");

                    b.HasIndex("PlayerId");

                    b.ToTable("MoraFieldingPerformances");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Opponent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Opponents");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentBattingPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BallsFaced")
                        .HasColumnType("integer");

                    b.Property<int>("BattingPosition")
                        .HasColumnType("integer");

                    b.Property<string>("BattingStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DismissalType")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<Guid?>("DismissedByMoraBowlerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FieldedByMoraPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Fours")
                        .HasColumnType("integer");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsNotOut")
                        .HasColumnType("boolean");

                    b.Property<int?>("MinutesBatted")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OpponentPlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Sixes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattingStyle");

                    b.HasIndex("DismissedByMoraBowlerId");

                    b.HasIndex("FieldedByMoraPlayerId");

                    b.HasIndex("InningsId");

                    b.HasIndex("OpponentPlayerId");

                    b.ToTable("OpponentBattingPerformances");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentBowlingPerformance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BowlingStyle")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<int>("Maidens")
                        .HasColumnType("integer");

                    b.Property<int>("NoBalls")
                        .HasColumnType("integer");

                    b.Property<Guid?>("OpponentPlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("OversBowled")
                        .HasColumnType("decimal(4,1)");

                    b.Property<string>("PlayerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RunsConceded")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wickets")
                        .HasColumnType("integer");

                    b.Property<int>("Wides")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BowlingStyle");

                    b.HasIndex("InningsId");

                    b.HasIndex("OpponentPlayerId");

                    b.ToTable("OpponentBowlingPerformances");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BattingStyle")
                        .HasColumnType("text");

                    b.Property<string>("BowlingStyle")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BattingStyle");

                    b.HasIndex("BowlingStyle");

                    b.HasIndex("OpponentId");

                    b.ToTable("OpponentPlayers");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OverSummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CumulativeRuns")
                        .HasColumnType("integer");

                    b.Property<int>("CumulativeWickets")
                        .HasColumnType("integer");

                    b.Property<int>("DotsInOver")
                        .HasColumnType("integer");

                    b.Property<int>("FoursInOver")
                        .HasColumnType("integer");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<int>("NoBallsInOver")
                        .HasColumnType("integer");

                    b.Property<int>("OverNumber")
                        .HasColumnType("integer");

                    b.Property<int>("RunsInOver")
                        .HasColumnType("integer");

                    b.Property<int>("SixesInOver")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WicketsInOver")
                        .HasColumnType("integer");

                    b.Property<int>("WidesInOver")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InningsId");

                    b.HasIndex("InningsId", "OverNumber")
                        .IsUnique();

                    b.ToTable("OverSummaries");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Partnership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Balls")
                        .HasColumnType("integer");

                    b.Property<int>("Batter1Runs")
                        .HasColumnType("integer");

                    b.Property<int>("Batter2Runs")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("EndedAtOver")
                        .HasColumnType("decimal(4,1)");

                    b.Property<Guid>("InningsId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MoraBatter1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MoraBatter2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OppBatter1Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OppBatter1Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("OppBatter2Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OppBatter2Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Runs")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartedAtOver")
                        .HasColumnType("decimal(4,1)");

                    b.Property<bool>("Unbroken")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WicketNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InningsId");

                    b.HasIndex("MoraBatter2Id");

                    b.HasIndex("OppBatter1Id");

                    b.HasIndex("OppBatter2Id");

                    b.HasIndex("InningsId", "IsActive");

                    b.HasIndex("MoraBatter1Id", "MoraBatter2Id");

                    b.ToTable("Partnerships");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BatchYear")
                        .HasColumnType("integer");

                    b.Property<string>("BattingStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DebutDate")
                        .HasColumnType("date");

                    b.Property<string>("Degree")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Faculty")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Nickname")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("PrimaryBowlingStyle")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BatchYear");

                    b.HasIndex("BattingStyle");

                    b.HasIndex("IsActive");

                    b.HasIndex("PrimaryBowlingStyle");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.PlayerMilestone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AchievedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<string>("MilestoneType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId", "MilestoneType")
                        .IsUnique();

                    b.ToTable("PlayerMilestones");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.PlayerSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BattingRole")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("PlayerId", "SeasonId")
                        .IsUnique();

                    b.ToTable("PlayerSeasons");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Tournament", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OversPerSide")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Venue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsMoraHomeGround")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.BowlingMilestone", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Delivery", "Delivery1")
                        .WithMany()
                        .HasForeignKey("Delivery1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Delivery", "Delivery2")
                        .WithMany()
                        .HasForeignKey("Delivery2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Delivery", "Delivery3")
                        .WithMany()
                        .HasForeignKey("Delivery3Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany()
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delivery1");

                    b.Navigation("Delivery2");

                    b.Navigation("Delivery3");

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Delivery", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "DismissedMoraBatter")
                        .WithMany()
                        .HasForeignKey("DismissedMoraBatterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "DismissedOppBatter")
                        .WithMany()
                        .HasForeignKey("DismissedOppBatterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("Deliveries")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraBatter")
                        .WithMany()
                        .HasForeignKey("MoraBatterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraBowler")
                        .WithMany()
                        .HasForeignKey("MoraBowlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraFielder")
                        .WithMany()
                        .HasForeignKey("MoraFielderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OppBatter")
                        .WithMany()
                        .HasForeignKey("OppBatterId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OppBowler")
                        .WithMany()
                        .HasForeignKey("OppBowlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DismissedMoraBatter");

                    b.Navigation("DismissedOppBatter");

                    b.Navigation("Innings");

                    b.Navigation("MoraBatter");

                    b.Navigation("MoraBowler");

                    b.Navigation("MoraFielder");

                    b.Navigation("OppBatter");

                    b.Navigation("OppBowler");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.FallOfWicket", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "DismissedMoraPlayer")
                        .WithMany()
                        .HasForeignKey("DismissedMoraPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "DismissedOppPlayer")
                        .WithMany()
                        .HasForeignKey("DismissedOppPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("FallOfWickets")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DismissedMoraPlayer");

                    b.Navigation("DismissedOppPlayer");

                    b.Navigation("Innings");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Innings", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Match", "Match")
                        .WithMany("Innings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraWickekeeper")
                        .WithMany()
                        .HasForeignKey("MoraWickeeperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Match");

                    b.Navigation("MoraWickekeeper");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.InningsEvent", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("Events")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Match", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraCaptain")
                        .WithMany()
                        .HasForeignKey("MoraCaptainId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraWickekeeper")
                        .WithMany()
                        .HasForeignKey("MoraWickeeperId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Opponent", "Opponent")
                        .WithMany("Matches")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "PlayerOfMatchMora")
                        .WithMany()
                        .HasForeignKey("PlayerOfMatchMoraId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Venue", "Venue")
                        .WithMany("Matches")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("MoraCaptain");

                    b.Navigation("MoraWickekeeper");

                    b.Navigation("Opponent");

                    b.Navigation("PlayerOfMatchMora");

                    b.Navigation("Tournament");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MatchOpponentSquad", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OpponentPlayer")
                        .WithMany()
                        .HasForeignKey("OpponentPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Match");

                    b.Navigation("OpponentPlayer");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MatchSquad", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Match", "Match")
                        .WithMany("Squad")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("MatchSquads")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBattingOrder", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany()
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBattingPerformance", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "DismissedByOppBowler")
                        .WithMany()
                        .HasForeignKey("DismissedByOppBowlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "FieldedByMoraPlayer")
                        .WithMany()
                        .HasForeignKey("FieldedByMoraPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("MoraBattingPerformances")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("BattingPerformances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DismissedByOppBowler");

                    b.Navigation("FieldedByMoraPlayer");

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraBowlingPerformance", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("MoraBowlingPerformances")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("BowlingPerformances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.MoraFieldingPerformance", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("MoraFieldingPerformances")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("FieldingPerformances")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Innings");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentBattingPerformance", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "DismissedByMoraBowler")
                        .WithMany()
                        .HasForeignKey("DismissedByMoraBowlerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "FieldedByMoraPlayer")
                        .WithMany()
                        .HasForeignKey("FieldedByMoraPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("OpponentBattingPerformances")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OpponentPlayer")
                        .WithMany()
                        .HasForeignKey("OpponentPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DismissedByMoraBowler");

                    b.Navigation("FieldedByMoraPlayer");

                    b.Navigation("Innings");

                    b.Navigation("OpponentPlayer");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentBowlingPerformance", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("OpponentBowlingPerformances")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OpponentPlayer")
                        .WithMany()
                        .HasForeignKey("OpponentPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Innings");

                    b.Navigation("OpponentPlayer");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OpponentPlayer", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Opponent", "Opponent")
                        .WithMany("Players")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Opponent");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.OverSummary", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("OverSummaries")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Innings");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Partnership", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Innings", "Innings")
                        .WithMany("Partnerships")
                        .HasForeignKey("InningsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraBatter1")
                        .WithMany()
                        .HasForeignKey("MoraBatter1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "MoraBatter2")
                        .WithMany()
                        .HasForeignKey("MoraBatter2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OppBatter1")
                        .WithMany()
                        .HasForeignKey("OppBatter1Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MoraCricketHub.Domain.Entities.OpponentPlayer", "OppBatter2")
                        .WithMany()
                        .HasForeignKey("OppBatter2Id")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Innings");

                    b.Navigation("MoraBatter1");

                    b.Navigation("MoraBatter2");

                    b.Navigation("OppBatter1");

                    b.Navigation("OppBatter2");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.PlayerMilestone", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("Milestones")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.PlayerSeason", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Player", "Player")
                        .WithMany("Seasons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MoraCricketHub.Domain.Entities.Season", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Tournament", b =>
                {
                    b.HasOne("MoraCricketHub.Domain.Entities.Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Innings", b =>
                {
                    b.Navigation("Deliveries");

                    b.Navigation("Events");

                    b.Navigation("FallOfWickets");

                    b.Navigation("MoraBattingPerformances");

                    b.Navigation("MoraBowlingPerformances");

                    b.Navigation("MoraFieldingPerformances");

                    b.Navigation("OpponentBattingPerformances");

                    b.Navigation("OpponentBowlingPerformances");

                    b.Navigation("OverSummaries");

                    b.Navigation("Partnerships");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Match", b =>
                {
                    b.Navigation("Innings");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Opponent", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Players");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Player", b =>
                {
                    b.Navigation("BattingPerformances");

                    b.Navigation("BowlingPerformances");

                    b.Navigation("FieldingPerformances");

                    b.Navigation("MatchSquads");

                    b.Navigation("Milestones");

                    b.Navigation("Seasons");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Season", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Tournament", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("MoraCricketHub.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
